spring.application.name=api-example

spring.datasource.url=jdbc:postgresql://aws-0-ca-central-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.lkjfrrupfajzcmcrwles
spring.datasource.password=vw6gtSutxTW7GKDG
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

supabase.url=https://lkjfrrupfajzcmcrwles.supabase.co
supabase.bucket=proveedores
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxramZycnVwZmFqemNtY3J3bGVzIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4NjU4MzI0MSwiZXhwIjoyMTAyMTU5MjQxfQ.p7pJ04okkwaz1TZVpXgrJ-hjCY0umDX3_rsiw4i3zic